In [1]:
import pandas as pd 
import numpy as np
dataset_labeled = pd.read_csv('dataset_labeled.csv')
dataset_labeled

,Unnamed: 0,no_of_adults,no_of_children,no_of_weekend_nights,no_of_week_nights,required_car_parking_space,lead_time,arrival_year,arrival_month,arrival_date,...,room_type_reserved_Room_Type 6,room_type_reserved_Room_Type 7,market_segment_type_Aviation,market_segment_type_Complementary,market_segment_type_Corporate,market_segment_type_Offline,market_segment_type_Online,booking_status_Canceled,booking_status_Not_Canceled,label_avg_price_per_room
0,0,2,0,1,2,0,224,2017,10,2,...,0,0,0,0,0,1,0,0,1,1
1,1,2,0,2,3,0,5,2018,11,6,...,0,0,0,0,0,0,1,0,1,2
2,2,1,0,2,1,0,1,2018,2,28,...,0,0,0,0,0,0,1,1,0,1
3,3,2,0,0,2,0,211,2018,5,20,...,0,0,0,0,0,0,1,1,0,2
4,4,2,0,1,1,0,48,2018,4,11,...,0,0,0,0,0,0,1,1,0,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
36270,36270,3,0,2,6,0,85,2018,8,3,...,0,0,0,0,0,0,1,0,1,3
36271,36271,2,0,1,3,0,228,2018,10,17,...,0,0,0,0,0,0,1,1,0,2
36272,36272,2,0,2,6,0,148,2018,7,1,...,0,0,0,0,0,0,1,0,1,2
36273,36273,2,0,0,3,0,63,2018,4,21,...,0,0,0,0,0,0,1,1,0,2
36274,36274,2,0,1,2,0,207,2018,12,30,...,0,0,0,0,0,1,0,0,1,3

In [2]:
dataset_labeled.columns
columns = []

columns.append('label_avg_price_per_room')
for i in range(len(dataset_labeled.columns[:-1])):
    columns.append(dataset_labeled.columns[i])

dataset_labeled = dataset_labeled[columns]
dataset_labeled

,label_avg_price_per_room,Unnamed: 0,no_of_adults,no_of_children,no_of_weekend_nights,no_of_week_nights,required_car_parking_space,lead_time,arrival_year,arrival_month,...,room_type_reserved_Room_Type 5,room_type_reserved_Room_Type 6,room_type_reserved_Room_Type 7,market_segment_type_Aviation,market_segment_type_Complementary,market_segment_type_Corporate,market_segment_type_Offline,market_segment_type_Online,booking_status_Canceled,booking_status_Not_Canceled
0,1,0,2,0,1,2,0,224,2017,10,...,0,0,0,0,0,0,1,0,0,1
1,2,1,2,0,2,3,0,5,2018,11,...,0,0,0,0,0,0,0,1,0,1
2,1,2,1,0,2,1,0,1,2018,2,...,0,0,0,0,0,0,0,1,1,0
3,2,3,2,0,0,2,0,211,2018,5,...,0,0,0,0,0,0,0,1,1,0
4,2,4,2,0,1,1,0,48,2018,4,...,0,0,0,0,0,0,0,1,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
36270,3,36270,3,0,2,6,0,85,2018,8,...,0,0,0,0,0,0,0,1,0,1
36271,2,36271,2,0,1,3,0,228,2018,10,...,0,0,0,0,0,0,0,1,1,0
36272,2,36272,2,0,2,6,0,148,2018,7,...,0,0,0,0,0,0,0,1,0,1
36273,2,36273,2,0,0,3,0,63,2018,4,...,0,0,0,0,0,0,0,1,1,0
36274,3,36274,2,0,1,2,0,207,2018,12,...,0,0,0,0,0,0,1,0,0,1

In [3]:
dataset_labeled = dataset_labeled.drop(columns = ['Unnamed: 0'])
dataset_labeled

,label_avg_price_per_room,no_of_adults,no_of_children,no_of_weekend_nights,no_of_week_nights,required_car_parking_space,lead_time,arrival_year,arrival_month,arrival_date,...,room_type_reserved_Room_Type 5,room_type_reserved_Room_Type 6,room_type_reserved_Room_Type 7,market_segment_type_Aviation,market_segment_type_Complementary,market_segment_type_Corporate,market_segment_type_Offline,market_segment_type_Online,booking_status_Canceled,booking_status_Not_Canceled
0,1,2,0,1,2,0,224,2017,10,2,...,0,0,0,0,0,0,1,0,0,1
1,2,2,0,2,3,0,5,2018,11,6,...,0,0,0,0,0,0,0,1,0,1
2,1,1,0,2,1,0,1,2018,2,28,...,0,0,0,0,0,0,0,1,1,0
3,2,2,0,0,2,0,211,2018,5,20,...,0,0,0,0,0,0,0,1,1,0
4,2,2,0,1,1,0,48,2018,4,11,...,0,0,0,0,0,0,0,1,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
36270,3,3,0,2,6,0,85,2018,8,3,...,0,0,0,0,0,0,0,1,0,1
36271,2,2,0,1,3,0,228,2018,10,17,...,0,0,0,0,0,0,0,1,1,0
36272,2,2,0,2,6,0,148,2018,7,1,...,0,0,0,0,0,0,0,1,0,1
36273,2,2,0,0,3,0,63,2018,4,21,...,0,0,0,0,0,0,0,1,1,0
36274,3,2,0,1,2,0,207,2018,12,30,...,0,0,0,0,0,0,1,0,0,1

In [4]:
# let variables between 0-2 for xgboost use
def xgboost_label(room_price_label):
    if room_price_label == 1:
        return 0
    elif room_price_label == 2:
        return 1
    else:
        return 2

In [5]:
dataset_labeled['label_avg_price_per_room'] = dataset_labeled['label_avg_price_per_room'].apply(lambda x: xgboost_label(x))

In [6]:
dataset_labeled

,label_avg_price_per_room,no_of_adults,no_of_children,no_of_weekend_nights,no_of_week_nights,required_car_parking_space,lead_time,arrival_year,arrival_month,arrival_date,...,room_type_reserved_Room_Type 5,room_type_reserved_Room_Type 6,room_type_reserved_Room_Type 7,market_segment_type_Aviation,market_segment_type_Complementary,market_segment_type_Corporate,market_segment_type_Offline,market_segment_type_Online,booking_status_Canceled,booking_status_Not_Canceled
0,0,2,0,1,2,0,224,2017,10,2,...,0,0,0,0,0,0,1,0,0,1
1,1,2,0,2,3,0,5,2018,11,6,...,0,0,0,0,0,0,0,1,0,1
2,0,1,0,2,1,0,1,2018,2,28,...,0,0,0,0,0,0,0,1,1,0
3,1,2,0,0,2,0,211,2018,5,20,...,0,0,0,0,0,0,0,1,1,0
4,1,2,0,1,1,0,48,2018,4,11,...,0,0,0,0,0,0,0,1,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
36270,2,3,0,2,6,0,85,2018,8,3,...,0,0,0,0,0,0,0,1,0,1
36271,1,2,0,1,3,0,228,2018,10,17,...,0,0,0,0,0,0,0,1,1,0
36272,1,2,0,2,6,0,148,2018,7,1,...,0,0,0,0,0,0,0,1,0,1
36273,1,2,0,0,3,0,63,2018,4,21,...,0,0,0,0,0,0,0,1,1,0
36274,2,2,0,1,2,0,207,2018,12,30,...,0,0,0,0,0,0,1,0,0,1

In [50]:
from sklearn.model_selection import train_test_split

df_treinamento, df_teste = train_test_split(dataset_labeled, test_size=0.3, random_state=40)

In [51]:
df_treinamento.shape

(25392, 32)

In [52]:
df_teste.shape

(10883, 32)

In [92]:
X_teste = df_teste.iloc[:,1:len(dataset_labeled)].values
X_teste

array([[2, 0, 2, ..., 0, 0, 1],
       [2, 1, 2, ..., 1, 1, 0],
       [2, 0, 2, ..., 1, 1, 0],
       ...,
       [2, 0, 2, ..., 1, 0, 1],
       [2, 0, 0, ..., 0, 0, 1],
       [1, 0, 0, ..., 0, 0, 1]])

In [54]:
X_teste.shape

(10883, 31)

In [55]:
Y_teste = df_teste.iloc[:, 0].values
Y_teste

array([0, 2, 2, ..., 1, 0, 1])

In [56]:
Y_teste.shape

(10883,)

In [57]:
df_treinamento.to_csv('hotel-reservations-train-xgboost.csv', header = False, index = False)
df_teste.to_csv('hotel-reservations-test-xgboost.csv', header = False, index = False)

In [58]:
import sagemaker
import boto3
from sagemaker import Session

In [ ]:
# set default credentials
boto3.setup_default_session(region_name='us-east-1')

# create session
session = sagemaker.Session()

# define bucket, folders and keys
bucket = ''
subpasta_modelo = 'modelos/hotel-reservations/xgboost'
subpasta_dataset = 'dataset/hotel-reservations'
key_train = 'hotel-train-data-xgboost'
key_test = 'hotel-test-data-xgboost'

role = sagemaker.get_execution_role()

# paths for train and test
s3_train_data = 's3://{}/{}/train/{}'.format(bucket, subpasta_dataset, key_train)
s3_test_data = 's3://{}/{}/test/{}'.format(bucket, subpasta_dataset, key_test)
output_location = 's3://{}/{}/output'.format(bucket, subpasta_modelo)

print('Role: {}'.format(role))

In [60]:
import os
with open('hotel-reservations-train-xgboost.csv', 'rb') as f:
  boto3.Session().resource('s3').Bucket(bucket).Object(os.path.join(subpasta_dataset, 'train', key_train)).upload_fileobj(f)

In [61]:
with open('hotel-reservations-test-xgboost.csv', 'rb') as f:
    boto3.Session().resource('s3').Bucket(bucket).Object(os.path.join(subpasta_dataset, 'test', key_test)).upload_fileobj(f)

In [ ]:
from sagemaker import image_uris
container = image_uris.retrieve(framework = 'xgboost', region=boto3.Session().region_name, version='latest')

In [63]:
xgboost = sagemaker.estimator.Estimator(image_uri = container,
                                        role = role,
                                        instance_count = 1,
                                        instance_type = 'ml.m5.2xlarge',
                                        output_path = output_location,
                                        sagemaker_session = session)

In [64]:
xgboost.set_hyperparameters(
    num_round=100,
    objective='multi:softprob',
    num_class=3
)

In [65]:
train_input = sagemaker.inputs.TrainingInput(s3_data = s3_train_data, content_type='csv', s3_data_type = 'S3Prefix')
validation_input = sagemaker.inputs.TrainingInput(s3_data = s3_test_data, content_type='csv', s3_data_type = 'S3Prefix')
data_channels = {'train': train_input, 'validation': validation_input}

In [ ]:
xgboost.fit(data_channels)

### Deploy

In [ ]:
xgboost_regressor = xgboost.deploy(initial_instance_count = 1, instance_type = 'ml.m4.xlarge')

In [70]:
from sagemaker.serializers import CSVSerializer
xgboost_regressor.serializer = CSVSerializer()

In [72]:
X_teste.shape, type(X_teste)

((10883, 31), numpy.ndarray)

In [71]:
#previsoes = np.array(xgboost_regressor.predict(X_teste).decode('utf-8'))
previsoes_bytes = xgboost_regressor.predict(X_teste)
previsoes_str = previsoes_bytes.decode('utf-8')
previsoes_list = eval(previsoes_str)
previsoes_array = np.array(previsoes_list)
previsoes_array

array([[6.95426404e-01, 2.83190578e-01, 2.13829931e-02],
       [3.21217813e-05, 1.06625631e-03, 9.98901606e-01],
       [2.15636548e-02, 2.44531438e-01, 7.33904898e-01],
       ...,
       [2.07697481e-01, 6.35669947e-01, 1.56632543e-01],
       [6.81924403e-01, 3.09994817e-01, 8.08075629e-03],
       [6.02333307e-01, 3.95391494e-01, 2.27521313e-03]])

In [74]:
predicted_labels = np.argmax(previsoes_array, axis=1)
predicted_labels

array([0, 2, 2, ..., 1, 0, 0])

In [75]:
Y_teste = np.array(Y_teste)
Y_teste

array([0, 2, 2, ..., 1, 0, 1])

In [76]:
import numpy as np
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, classification_report, confusion_matrix

accuracy = accuracy_score(Y_teste, predicted_labels)
precision = precision_score(Y_teste, predicted_labels, average='macro')
recall = recall_score(Y_teste, predicted_labels, average='macro')
f1 = f1_score(Y_teste, predicted_labels, average='macro')

In [77]:
print("Accuracy:", accuracy)
print("Precision:", precision)
print("Recall:", recall)
print("F1 Score:", f1)

Accuracy: 0.835890838923091
Precision: 0.8402563946923697
Recall: 0.8377285743280035
F1 Score: 0.8384330310659625

In [83]:
print(classification_report(Y_teste, predicted_labels))

              precision    recall  f1-score   support

           0       0.88      0.82      0.85      3308
           1       0.79      0.80      0.80      4127
           2       0.85      0.89      0.87      3448

    accuracy                           0.84     10883
   macro avg       0.84      0.84      0.84     10883
weighted avg       0.84      0.84      0.84     10883

In [84]:
cm = confusion_matrix(Y_teste, predicted_labels)
cm

array([[2710,  516,   82],
       [ 331, 3320,  476],
       [  37,  344, 3067]])

In [49]:
{
    "ParameterRanges": {
      "CategoricalParameterRanges": [],
      "ContinuousParameterRanges": [
        {
          "MaxValue": "1",
          "MinValue": "0",
          "Name": "eta"
        },
        {
          "MaxValue": "2",
          "MinValue": "0",
          "Name": "alpha"
        },
        {
          "MaxValue": "10",
          "MinValue": "1",
          "Name": "min_child_weight"
        }
      ],
      "IntegerParameterRanges": [
        {
          "MaxValue": "10",
          "MinValue": "1",
          "Name": "max_depth"
        }
      ],
      "IntegerParameterRanges": [
        {
          "MaxValue": "300",
          "MinValue": "50",
          "Name": "num_round"
        }
      ]
    },
    "ResourceLimits": {
      "MaxNumberOfTrainingJobs": 12,
      "MaxParallelTrainingJobs": 3
    },
    "Strategy": "Bayesian",
    "HyperParameterTuningJobObjective": {
      "MetricName": "validation:rmse",
      "Type": "Minimize"
    }
  }

{'ParameterRanges': {'CategoricalParameterRanges': [],
  'ContinuousParameterRanges': [{'MaxValue': '1',
    'MinValue': '0',
    'Name': 'eta'},
   {'MaxValue': '2', 'MinValue': '0', 'Name': 'alpha'},
   {'MaxValue': '10', 'MinValue': '1', 'Name': 'min_child_weight'}],
  'IntegerParameterRanges': [{'MaxValue': '300',
    'MinValue': '50',
    'Name': 'num_round'}]},
 'ResourceLimits': {'MaxNumberOfTrainingJobs': 12,
  'MaxParallelTrainingJobs': 3},
 'Strategy': 'Bayesian',
 'HyperParameterTuningJobObjective': {'MetricName': 'validation:rmse',
  'Type': 'Minimize'}}

In [ ]:
training_job_definition = {
    "AlgorithmSpecification": {
      "TrainingImage": container,
      "TrainingInputMode": "File"
    },
    "InputDataConfig": [
      {
        "ChannelName": "train",
        "CompressionType": "None",
        "ContentType": "csv",
        "DataSource": {
          "S3DataSource": {
            "S3DataDistributionType": "FullyReplicated",
            "S3DataType": "S3Prefix",
            "S3Uri": s3_train_data
          }
        }
      },
      {
        "ChannelName": "validation",
        "CompressionType": "None",
        "ContentType": "csv",
        "DataSource": {
          "S3DataSource": {
            "S3DataDistributionType": "FullyReplicated",
            "S3DataType": "S3Prefix",
            "S3Uri": s3_test_data
          }
        }
      }
    ],
    "OutputDataConfig": {
      "S3OutputPath": "s3://{}/{}/output".format(bucket,subpasta_modelo)
    },
    "ResourceConfig": {
      "InstanceCount": 2,
      "InstanceType": "ml.c4.2xlarge",
      "VolumeSizeInGB": 10
    },
    "RoleArn": role,
    "StaticHyperParameters": {
      "eval_metric": "merror",
      "objective": "multi:softprob",

      "rate_drop": "0.3",
      "tweedie_variance_power": "1.4"
    },
    "StoppingCondition": {
      "MaxRuntimeInSeconds": 43200
    }
}

### Tuning

In [88]:
tuning_job_config = {
  "ParameterRanges": {
    "CategoricalParameterRanges": [],
    "ContinuousParameterRanges": [
      {
        "MaxValue": "1",
        "MinValue": "0",
        "Name": "eta"
      },
      {
        "MaxValue": "2",
        "MinValue": "0",
        "Name": "alpha"
      },
      {
        "MaxValue": "10",
        "MinValue": "1",
        "Name": "min_child_weight"
      }
    ],
    "IntegerParameterRanges": [
      {
        "MaxValue": "10",
        "MinValue": "1",
        "Name": "max_depth"
      },
      {
        "MaxValue": "300",
        "MinValue": "50",
        "Name": "num_round"
      }
    ]
  },
  "ResourceLimits": {
    "MaxNumberOfTrainingJobs": 9,
    "MaxParallelTrainingJobs": 3
  },
  "Strategy": "Bayesian",
  "HyperParameterTuningJobObjective": {
    "MetricName": "validation:merror",
    "Type": "Minimize"
  }
}

In [89]:
training_job_definition = {
    "AlgorithmSpecification": {
      "TrainingImage": container,
      "TrainingInputMode": "File"
    },
    "InputDataConfig": [
      {
        "ChannelName": "train",
        "CompressionType": "None",
        "ContentType": "csv",
        "DataSource": {
          "S3DataSource": {
            "S3DataDistributionType": "FullyReplicated",
            "S3DataType": "S3Prefix",
            "S3Uri": s3_train_data
          }
        }
      },
      {
        "ChannelName": "validation",
        "CompressionType": "None",
        "ContentType": "csv",
        "DataSource": {
          "S3DataSource": {
            "S3DataDistributionType": "FullyReplicated",
            "S3DataType": "S3Prefix",
            "S3Uri": s3_test_data
          }
        }
      }
    ],
    "OutputDataConfig": {
      "S3OutputPath": "s3://{}/{}/output".format(bucket,subpasta_modelo)
    },
    "ResourceConfig": {
      "InstanceCount": 2,
      "InstanceType": "ml.c4.2xlarge",
      "VolumeSizeInGB": 10
    },
    "RoleArn": role,
    "StaticHyperParameters": {
      "eval_metric": "merror",
      "objective": "multi:softprob",
      "num_class": "3",
    },
    "StoppingCondition": {
      "MaxRuntimeInSeconds": 43200
    }
}

In [91]:
smclient = boto3.client('sagemaker')
smclient.create_hyper_parameter_tuning_job(HyperParameterTuningJobName = "xgboosttuninghotelres",
                                          HyperParameterTuningJobConfig = tuning_job_config,
                                          TrainingJobDefinition = training_job_definition)

{'HyperParameterTuningJobArn': 'arn:aws:sagemaker:us-east-1:730335411831:hyper-parameter-tuning-job/xgboosttuninghotelres',
 'ResponseMetadata': {'RequestId': '167a57a4-f9ea-4d2a-8ab5-163b0e504ba4',
  'HTTPStatusCode': 200,
  'HTTPHeaders': {'x-amzn-requestid': '167a57a4-f9ea-4d2a-8ab5-163b0e504ba4',
   'content-type': 'application/x-amz-json-1.1',
   'content-length': '122',
   'date': 'Wed, 22 May 2024 13:07:27 GMT'},
  'RetryAttempts': 0}}